name: ZMK User Config Build

on:  
  workflow_call:  
    inputs:  
      shield:  
        required: false  
        type: string  
        default: lily58
      board:  
        required: false  
        type: string  
        default: nice_nano_v2  
      debug:  
        required: false  
        type: boolean  
        default: false  

jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout Repository  
        uses: actions/checkout@v3  

      - name: Setup ZMK Build Environment
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install -y git cmake ninja-build gperf \
              ccache dfu-util dfu-programmer gcc \
              python3-pip python3-setuptools python3-wheel
          
          pip3 install -U west
          export PATH="$HOME/.local/bin:$PATH"
      
          if ! command -v west &> /dev/null; then
            echo "West não encontrado após a instalação. Abortando."
            exit 1
          fi
      
          if [ ! -d "zmk" ]; then
            git clone https://github.com/zmkfirmware/zmk.git
            cd zmk
            west init -l config
            west update
            west zephyr-export
          else
            echo "Repositório ZMK já presente."
          fi
      
          cd zmk
          west update
          west zephyr-export

      - name: Install Python Dependencies
        run: |
          cd zmk
          if [ -f "zephyr/scripts/requirements-base.txt" ]; then
            pip3 install -r zephyr/scripts/requirements-base.txt
          else
            echo "Arquivo requirements-base.txt não encontrado. Criando um novo..."
            mkdir -p zephyr/scripts
            cat <<EOT > zephyr/scripts/requirements-base.txt
            west
            cmake
            ninja
            gperf
            pyelftools
            EOT
            pip3 install -r zephyr/scripts/requirements-base.txt
          fi

      - name: Build Firmware
        run: |
          cd zmk/app
          west build -p auto -b ${{ inputs.board }} -- -DSHIELD=${{ inputs.shield }}

      - name: Upload Firmware Artifacts  
        uses: actions/upload-artifact@v4  
        with:  
          name: zmk-firmware  
          path: build/zephyr/zmk.uf2
