name: Build ZMK firmware

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: ./.github/workflows/build-user-config.yml
    with:
      shield: lily58
      board: nice_nano_v2
      debug: false
