name: ZMK User Config Build

on:  
  workflow_call:  
    inputs:  
      shield:  
        required: false  
        type: string  
        default: lily58  # Nome do shield já configurado como padrão
      board:  
        required: false  
        type: string  
        default: nrf52840dk_nrf52840  
      debug:  
        required: false  
        type: boolean  
        default: false  

jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout Repository  
        uses: actions/checkout@v3  

      - name: Setup ZMK Build Environment
        run: |
          sudo apt update -y
          sudo apt install -y git cmake ninja-build gperf \
              ccache dfu-util dfu-programmer gcc \
              python3-pip python3-setuptools python3-wheel \
              unzip wget
          
          pip3 install -U west
          export PATH="$HOME/.local/bin:$PATH"
      
          if ! command -v west &> /dev/null; then
            echo "West não encontrado após a instalação. Abortando."
            exit 1
            fi
            echo "Cloning ZMK repository..."
            git clone https://github.com/zmkfirmware/zmk.git zmk || {
            echo "Erro: Falha ao clonar o repositório ZMK. Verifique a conectividade de rede e as permissões."
            exit 1
            }
      
          echo "Inicializando o repositório ZMK como subprojeto..."
          if [ ! -f "west.yml" ]; then
            echo "Erro: Arquivo west.yml não encontrado no diretório raiz. Certifique-se de que ele existe e está correto."
            exit 1
          fi
          west init -l .

          echo "Validando o arquivo west.yml..."
          if ! grep -q "manifest:" west.yml; then
            echo "Erro: O arquivo west.yml parece inválido. Verifique seu conteúdo."
            cat west.yml
            exit 1
          fi

          west update

          echo "Verificando se o diretório 'zmk' foi criado após o west update..."
          if [ ! -d "zmk" ]; then
            echo "Erro: O diretório 'zmk' não foi criado após o west update. Depurando o problema..."
            echo "Conteúdo do arquivo west.yml:"
            cat west.yml || echo "Arquivo west.yml não encontrado."

            echo "Verificando o estado do repositório git:"
            git status

            echo "Tentando recriar o diretório 'zmk'..."
            rm -rf zmk
            west update
            if [ ! -d "zmk" ]; then
              echo "Erro crítico: O diretório 'zmk' ainda não foi criado após a tentativa de recriação. Verifique o arquivo west.yml e as permissões do sistema."
              exit 1
            fi
          fi

          echo "Verificando o conteúdo do diretório zmk para depuração:"
          ls -l zmk

          echo "Verifying ZMK directory..."
          cd zmk
          if [ ! -d "app" ]; then
            echo "Erro: O diretório 'app' não existe dentro de 'zmk'. Verifique o repositório ZMK."
            exit 1
          fi
          echo "Listando arquivos no diretório zmk/app para depuração:"
          ls -l app
          if [ -f "app/west.yml" ]; then
            echo "west.yml encontrado no diretório zmk/app. Inicializando west..."
            west init -l app
          else
            echo "west.yml não encontrado no diretório zmk/app. Abortando."
            exit 1
          fi
          west update
          west zephyr-export

      - name: Install Python Dependencies
        run: |
          cd zmk
          if [ -f "zephyr/scripts/requirements-base.txt" ]; then
            pip3 install -r zephyr/scripts/requirements-base.txt
          else
            echo "Arquivo requirements-base.txt não encontrado. Criando um novo..."
            mkdir -p zephyr/scripts
            cat <<EOT > zephyr/scripts/requirements-base.txt
          west
          cmake
          ninja
          gperf
          pyelftools
          EOT
            pip3 install -r zephyr/scripts/requirements-base.txt
          fi

      - name: List Available Shields
        run: |
          cd zmk/app
          ls -1 boards/shields

      - name: Validate Shield
        run: |
          cd zmk/app
          if ! west list | grep -q "boards/shields/${{ inputs.shield }}"; then
            echo "Erro: SHIELD '${{ inputs.shield }}' não é válido. Verifique o nome do shield."
            exit 1
          fi

      - name: Build Firmware
        run: |
          cd zmk/app
          west build -p auto -b ${{ inputs.board }} -- -DSHIELD=${{ inputs.shield }}

      - name: Upload Firmware Artifacts  
        uses: actions/upload-artifact@v4  
        with:  
          name: zmk-firmware  
          path: build/zephyr/zmk.uf2
